apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: kube-system
spec:
  containers:
  - name: test
    image: alpine
    command:
    - sleep
    args:
    - '60000'
    volumeMounts:
    - name: test-vol
      mountPath: /test
  volumes:
  - name: test-vol
    glusterfs:
      endpoints: glusterfs-cluster
      path: test
