apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-brick-2
  namespace: kube-system
  labels:
    type: "host-path"
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/brick
